[package]
name = "plasma-pilot-atspi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "AT-SPI accessibility backend for PlasmaPilot."

[dependencies]
libplasma-pilot.workspace = true
plasma-pilot-backend.workspace = true

[lints]
workspace = true
