[package]
name = "seatgeist-atspi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "AT-SPI accessibility backend for Seatgeist."

[dependencies]
async-trait.workspace = true
libseatgeist.workspace = true
seatgeist-backend.workspace = true
tokio.workspace = true
wait-timeout.workspace = true
zbus.workspace = true

[lints]
workspace = true
