[Unit]
After=plasma-kwin_wayland.service plasma-xdg-desktop-portal-kde.service
Wants=plasma-xdg-desktop-portal-kde.service
PartOf=plasma-kwin_wayland.service

[Service]
Restart=on-failure
RestartSec=2s
