[package]
name = "plasma-pilot-kwin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "KWin integration backend for PlasmaPilot."

[dependencies]
libplasma-pilot.workspace = true
plasma-pilot-backend.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
