[package]
name = "plasma-pilot-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Mock backends and fixtures for PlasmaPilot tests."

[dependencies]
async-trait.workspace = true
libplasma-pilot.workspace = true
plasma-pilot-backend.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
