[package]
name = "seatgeist-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Mock backends and fixtures for Seatgeist tests."

[dependencies]
async-trait.workspace = true
libseatgeist.workspace = true
seatgeist-backend.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
